### ISSUE TITLE
DBに新たなカラムの追加

### ISSUE THREAD

**Issue by SatoTatsuhiro** [shin-kanouchi/SLOT_API#3]
# カラムの一覧
* 機種番号
* 機種名
* 読み
* 台のタイプ (1:AT 2:ART 3:A 4:RT)
* 天井G
* 狙い目文言
* 初当たり確率
* 1kあたりの回転数
* 計算type
* 天井期待値(二次元配列)
* サムネイル画像
* 詳細画面の画像

**Comment by SatoTatsuhiro** [comment]
これあってるか確認頼んだー
@shin-kanouchi

**Comment by shin-kanouchi** [comment]
日本語のカラム (英語のカラム) [具体例]
- 機種番号(id)
[1]
- 機種名(name)
[アナザーゴッドハーデス]
- 読み(pronunciation)
[あなざーごっどはーです]
- 台のタイプ(machine_type) [1]
 1. AT 
 2. ART 
 3. A 
 4. RT
- 天井G(limit)
[1570]
- 狙い目文言(aim_label)
[通常時900G]
- 初当たり確率(bounus_prob) [459]
- 1kあたりの回転数(k_game_count)
[28]
- 計算type(calcutation_type) [1]
 - 0 計算できない
 - 1 ほとんどのやつ
 - 2 Aタイプでボナごとに天井が違う
 - 3 なし 
- 天井期待値のG数リスト(expect_games) [600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400]
- 天井期待値の期待値リスト(expect_values) [1770, 3410, 5010, 6110, 8340, 11465, 14590, 19315, 24040]
- 導入日 (date) [201402]
- 機種ごとの詳細文(machine_detail) [長いので省略]
- サムネイル画像(machine_icon) [名前は全て"id".png(アナゴの場合は1.png)で保存してある]
- 詳細画面の画像(detail_image)[名前は全てdet"id".png(アナゴの場合はdet1.png)で保存してある]

**Comment by SatoTatsuhiro** [comment]
できたお
